---
# Install drivers for TP-LINK 725N WiFi dongle (chipset rtl8188eu) 
# https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371

- name: Download driver install script
  get_url: 
    url=https://dl.dropboxusercontent.com/u/80256631/install-8188eu.tgz
    dest=/tmp

- name: Unarchive driver install script
  unarchive: src=/tmp/install-8188eu.tgz dest=/tmp copy=no

- name: execute driver install script
  shell: ./install-8188eu.sh >> /home/{{ ansible_ssh_user }}/install-8188eu.log chdir=/tmp
  sudo: yes

# This chipset needs a custom hostapd, so lets download, compile and install it
# http://www.jenssegers.be/blog/43/Realtek-RTL8188-based-access-point-on-Raspberry-Pi

- name: Remove previous hostapd, if it exists
  apt: pkg=hostapd state=absent
  sudo: yes
  
- name: Download custom hostapd sources
  get_url: 
    url=https://github.com/jenssegers/RTL8188-hostapd/archive/v2.0.tar.gz
    dest=/tmp

- name: Unarchive hostapd sources 
  unarchive: src=/tmp/RTL8188-hostapd-2.0.tar.gz dest=/tmp copy=no

- command: make
  args:
    chdir: "/tmp/RTL8188-hostapd-2.0/hostapd"

- command: sudo make install
  args:
    chdir: "/tmp/RTL8188-hostapd-2.0/hostapd"
    
- name: Fix boot system symlink for hostapd
  command: ln -s /etc/init.d/hostapd /etc/rc2.d/S02hostapd
  sudo: yes