---
- hosts: all
  remote_user: pi
  gather_facts: yes
  sudo: yes

  handlers:
    - include: ../../handlers/handlers.yml

  vars:
    - hostname: freya
    - root_ro_enabled: false

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: huawei_e3372h
    - role: upnpc
      upnpc_interface: eth1
      upnpc_port_forwards: "500 UDP 4500 UDP 1701 UDP"
    - canboat
    - mcp2515-can
    - crda_domain
    - role: aws-cli
      aws_access_key_id: "{{ chacal.aws.freyalogs.access_key }}"
      aws_secret_access_key: "{{ chacal.aws.freyalogs.secret_key }}"
    - role: nat_router
      nat_router_local_interface: eth0
      nat_router_inet_interface: eth1
      nat_router_ip: 10.90.100.1
      nat_router_dhcp_range: "10.90.100.50,10.90.100.150,24h"
    - role: l2tp_vpn_server
      l2tp_vpn_psk: "{{ chacal.l2tp_vpn_psk }}"
      l2tp_vpn_local_ip: 10.90.100.1
      l2tp_vpn_local_ip_range: 10.90.100.200-10.90.100.250
    - role: inadyn_ddns
      inadyn_ddns_username: "{{ chacal.inadyn_ddns_username }}"
      inadyn_ddns_password: "{{ chacal.inadyn_ddns_password }}"
      inadyn_ddns_hostname: "{{ chacal.inadyn_ddns_hostname.freya }}"
    - root-ro