# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Run setup first, then this:
# ansible-playbook -i hosts site.yml

- hosts: all
  remote_user: pi
  gather_facts: yes
  sudo: yes

  vars:
    - hostname: cassiopeia

  roles:
    - common
    - huawei_e3372h
    - hotspot
    - role: nat_router
      nat_router_fw_input_rules:
        - "-A FORWARD -i eth1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
        - "-A FORWARD -i wlan0 -o eth1 -j ACCEPT"
        - "-A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
        - "-A FORWARD -i eth0 -o eth1 -j ACCEPT"
      nat_router_inet_interface: eth1
    - canboat
    - node
    - role: node-app
      node_app_name: "signalk-server"
      node_app_git_repo: "https://github.com/SignalK/signalk-server-node.git"
      node_app_main: "bin/signalk-server"

  handlers:
    - include: handlers/handlers.yml
