---
- name: Download canboat
  git: repo=https://github.com/canboat/canboat.git dest={{ canboat_path }} clone=yes

- command: make
  args:
    chdir: "{{ canboat_path }}"

- command: sudo make install
  args:
    chdir: "{{ canboat_path }}"
  ignore_errors: yes  # can't help the way Makefile is written...
 