---
- name: Enable SPI
  lineinfile: dest=/boot/config.txt regexp='^#(dtparam=spi=on)$' line='\1' backrefs=yes
  notify: reboot

- name: Enable SPI overlay
  lineinfile: dest=/boot/config.txt line='dtoverlay=spi-bcm2835-overlay'
  notify: reboot

- name: Setup MCP2515 can device
  lineinfile: dest=/boot/config.txt line="dtoverlay=mcp2515-{{ mcp2515_can_device }}-overlay,oscillator={{ mcp2515_oscillator_freq }},interrupt={{ mcp2515_int_pin }}"
  notify: reboot

- name: Bring up CAN device on boot
  lineinfile:
    dest: /etc/rc.local
    regexp: '^ip link set {{ mcp2515_can_device }} up type can bitrate'
    line: "ip link set {{ mcp2515_can_device }} up type can bitrate {{ mcp2515_bitrate }}"
    insertbefore: "^exit 0$"
  notify: reboot

- name: Set CAN device tx queue length on boot
  lineinfile:
    dest: /etc/rc.local
    regexp: '^ip link set {{ mcp2515_can_device }} txqueuelen'
    line: "ip link set {{ mcp2515_can_device }} txqueuelen {{ mcp2515_tx_queuelen }}"
    insertafter: "^ip link set {{ mcp2515_can_device }} up"
  notify: reboot

- name: Install can-utils
  apt: pkg=can-utils state=latest
