---
mcp2515_can_device: can0
mcp2515_oscillator_freq: 8000000  # 8MHz by default, this must match the crystal on the MCP2515 module
mcp2515_int_pin: 22               # GPIO pin number to which the MCP module's interrupt pin is connected
mcp2515_bitrate: 250000           # NMEA2000 bus operates at 250kbps
mcp2515_tx_queuelen: 100