# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Download SignalK
  git: repo=https://github.com/SignalK/signalk-server-node.git dest={{ signalk_path }} clone=yes
  sudo: no

- name: Install SignalK
  npm: path={{ signalk_path }}
  sudo: no

- name: Install Bower
  npm: name=bower path={{ signalk_path }}
  sudo: no

# cannot get ansible bower module to behave, so...
- name: install sailgauge
  command: node_modules/.bin/bower install https://github.com/SignalK/sailgauge.git
  args:
    chdir: "{{ signalk_path }}"
  sudo: no

- name: install instrumentpanel
  command: node_modules/.bin/bower install https://github.com/SignalK/instrumentpanel.git
  args:
    chdir: "{{ signalk_path }}"
  sudo: no

- name: install simplegauges
  command: node_modules/.bin/bower install https://github.com/SignalK/simplegauges.git
  args:
    chdir: "{{ signalk_path }}"
  sudo: no

- name: install maptracker
  command: node_modules/.bin/bower install https://github.com/hkapanen/maptracker.git
  args:
    chdir: "{{ signalk_path }}"
  sudo: no