---
# Using custom hostapd for RTL8188eu chipset...
#- name: Install hostapd
#  apt: pkg=hostapd state=latest
#  sudo: yes

- name: Install DHCP server
  apt: pkg=isc-dhcp-server state=latest
  sudo: yes

- name: Copy the new DHCP configurations into place.
  copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  sudo: yes

- name: Tell DHCP server which interface to use.
  copy: src=isc-dhcp-server dest=/etc/default/isc-dhcp-server
  sudo: yes

- name: Update network interface configurations.
  copy: src=interfaces dest=/etc/network/interfaces
  sudo: yes

# Gotta reboot to make wlan0 available
- name: Reboot host
  shell: reboot
  sudo: yes  

- name: Wait for the host to restart
  local_action:
    module: wait_for
      host={{ ansible_ssh_host }}
      port=22
      delay=5
      timeout=300
              
- name: Assign static IP address to wireless interface.
  shell: ifconfig wlan0 192.168.74.1
  sudo: yes

- name: Move the hostapd file into place.
  copy: src=hostapd.conf dest=/etc/hostapd/hostapd.conf
  sudo: yes

- name: Input our chosen Radio chipset into the hostapd config file.
  lineinfile: dest=/etc/hostapd/hostapd.conf  regexp=^'driver=' line='driver={{ chipset }}'
  sudo: yes

- name: Input our chosen SSID into the hostapd config file.
  lineinfile: dest=/etc/hostapd/hostapd.conf  regexp=^'ssid=' line='ssid={{ ssid }}'
  sudo: yes

- name: Input our chosen passphrase into the hostapd config file.
  lineinfile: dest=/etc/hostapd/hostapd.conf regexp=^'wpa_passphrase=' line='wpa_passphrase={{ wpa_passphrase }}'
  sudo: yes

#- name: Point hostapd at the configurations file.
#  lineinfile: dest=/etc/default/hostapd.conf regexp=^'DAEMON_CONF=""' line='DAEMON_CONF="/etc/hostapd/hostapd.conf"'
#  sudo: yes

- name: Update NAT settings
  shell: echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  sudo: yes

- name: Activate NAT settings
  shell: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
  sudo: yes

- name: ifplugd configurations
  copy: src=ifplugd dest=/etc/default/ifplugd
  sudo: yes

- name: Flush IPTables
  shell: iptables -F
  sudo: yes

- name: Flush NAT routing table
  shell: iptables -t nat -F
  sudo: yes

- name: Copy IPTables config file over
  copy: src=iptables.conf dest=/tmp/iptables.conf
  sudo: yes

- name: Import IPTables config
  shell: iptables-restore < /tmp/iptables.conf
  sudo: yes

- name: Save IPTables configuration
  shell: sh -c "iptables-save > /etc/iptables.ipv4.nat"
  sudo: yes

- name: Make hostapd start at boot
  shell: update-rc.d hostapd enable
  sudo: yes

- name: Make isc-dhcp-server start at boot
  shell: update-rc.d isc-dhcp-server enable
  sudo: yes