#Assuming fresh Raspbian Jessie (2015-09-24)

---
- name: Set new hostname
  hostname: name={{ hostname }}
  sudo: yes

- name: New hostname also to /etc/hosts file
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='127.0.1.1 {{ hostname }}'
  sudo: yes
  
- name: Copy timezone file
  copy: src=timezone dest=/etc/timezone
  sudo: yes

- name: Set timezone
  command: dpkg-reconfigure -f noninteractive tzdata
  sudo: yes

- name: Update the apt cache
  apt: update_cache=yes
  sudo: yes

- name: Update the Raspbian distribution
  apt: upgrade=yes
  sudo: yes

- name: Install/update some basic tools
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - unattended-upgrades
    - build-essential
    - git
    - curl
    - htop
    - nmap
    - tmux
    - zsh
    - nmon
    - dstat
    - rpi-update
    - haveged
    - avahi-daemon 
    - rng-tools
    - netatalk
    - screen
    - dnsutils

- name: Uninstall unnecessary stuff
  apt: pkg={{ item }} state=absent
  sudo: yes
  with_items:
  - xserver-xorg-video-fbdev
  - xserver-xorg 
  - xinit
  - gstreamer1.0-x
  - gstreamer1.0-omx 
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-alsa
  - gstreamer1.0-libav
  - epiphany-browser
  - lxde
  - lxtask
  - menu-xdg
  - gksu
  - xserver-xorg-video-fbturbo
  - xpdf
  - gtk2-engines 
  - alsa-utils
  - netsurf-gtk 
  - zenity
  - desktop-base
  - lxpolkit
  - weston
  - omxplayer
  - raspberrypi-artwork
  - lightdm
  - gnome-themes-standard-data
  - gnome-icon-theme
  - qt50-snapshot
  - qt50-quick-particle-examples
  - idle
  - python3-pygame
  - python-pygame
  - python-tk
  - idle3
  - python3-tk
  - python-serial
  - python3-serial
  - python-picamera
  - python3-picamera
  - debian-reference-en
  - dillo
  - x2x
  - scratch
  - nuscratch
  - timidity
  - smartsim
  - penguinspuzzle
  - pistore
  - sonic-pi
  - python3-numpy
  - python3-pifacecommon
  - python3-pifacedigitalio
  - python3-pifacedigital-scratch-handler
  - python-pifacecommon
  - python-pifacedigitalio
  - oracle-java8-jdk
  - minecraft-pi
  - python-minecraftpi
  - wolfram-engine
  - libreoffice
  - claws-mail
  - greenfoot
  - bluej
  
- name: Autoremove any unused packages
  shell: "apt-get autoremove --assume-yes --purge"
  sudo: yes

- name: Autoclean the system
  shell: "apt-get autoclean --assume-yes"
  sudo: yes

- name: Cleanup the user home directory
  shell: "rm -rf /home/{{ ansible_ssh_user }}/*"

- name: Enforce HTTPS for all the GIT traffic
  command: 'git config --global url."https://github.com/".insteadOf git@github.com:'
  command: 'git config --global url."https://".insteadOf git://'

- name: Some shell aliases for the user
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc line="{{ item }}"
  with_items: 
  - "alias ll='ls -l'"
  - "alias la='ls -la'"
  - "alias lt='ls -lat'"
